# 陣列程式設計的五個元素

> 從登上 Nature 的 NumPy 論文暸解何謂 Array Programming。
>
> 標籤：程式設計

郭耀仁 <yaojenkuo@datainpoint.com> from [DATAINPOINT](https://datainpoint.substack.com/welcome)

## TL; DR

在這個專案中，我們打算使用 Python 的 NumPy 套件體驗五個陣列程式設計元素：資料結構（Data structure）、索引（Indexing）、向量化（Vectorization）、廣播（Broadcasting）與歸納（Reduction）。透過這個專案，我們能夠具體暸解 NumPy 是如何實現陣列程式設計。

## 載入 NumPy

In [1]:
import numpy as np

![](img/array-programming-five-elements.png)

## 資料結構（Data structure）

In [2]:
# create an array
arr = np.arange(12).reshape(4, -1)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
# common attributes
print(arr.size)
print(arr.shape)
print(arr.dtype)    # in bits
print(arr.itemsize) # in bytes

12
(4, 3)
int64
8


## 索引（Indexing）

In [4]:
arr[:, 1:]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [5]:
arr[:, :2:]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [6]:
arr[1, 2]

5

In [7]:
print(arr > 9)
print(arr[arr > 9])

[[False False False]
 [False False False]
 [False False False]
 [False  True  True]]
[10 11]


In [8]:
indexing = [0, 1], [1, 2]
arr[indexing]

array([1, 5])

In [9]:
indexing = [[1, ], [2, ]],[[1, 0]]
arr[indexing]

array([[4, 3],
       [7, 6]])

## 向量化（Vectorization）

In [10]:
x = arr[:, :2]
ones = np.ones((4, 2), dtype=int)
x + ones

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

## 廣播（Broadcasting）

In [11]:
x = arr[:, 0:1]
y = np.array([1, 2])
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

## 歸納（Reduction）

In [12]:
arr.sum(axis=0)

array([18, 22, 26])

In [13]:
arr.sum(axis=1)

array([ 3, 12, 21, 30])

In [14]:
arr.sum()

66